### ISSUE TITLE
mount-buildkite-agent doesn't work across platforms

### ISSUE THREAD

**Issue by sj26** [buildkite-plugins/docker-buildkite-plugin#154]
As mentioned in https://github.com/buildkite/agent/issues/1181, mount-buildkite-agent doesn't work when running a buildkite agent on a macos host and using something like docker for mac because it mounts a mac binary into a linux container.

There are a couple of options, we could at least raise a clear error message, or we could try to provision and make available a target platform-appropriate binary.

**Comment by sj26** [comment]
I am making a comment to test help scout synchronization.

**Comment by toote** [comment]
This issue can be more general than one believes due to architecture changes between the docker container and the agent host and would greatly depend on the version combination of docker and OS X.

Unfortunately, I don't see a way to solve this as one would need to ensure that the version being shared is not only compatible with the container itself but also the same version as the agent that is currently running (or you will probably run into a lot of issues when you are expecting them to be the same). So any suggestions are welcome.

That said sharing the agent in OS X has been disabled by default since 2018 so whoever wants to actually use the feature will have to do so on purpose and I believe we could expect them to be aware of such limitations. In any case, I have added a note on the matter in PR #211 (where the default value of the option is changed) so that people are more aware of this particular caveat.
