### ISSUE TITLE
Docker on Docker support

### ISSUE THREAD

**Issue by ShadySQL** [buildkite-plugins/docker-buildkite-plugin#190]
Trying to mount the docker socket to my container gives me a permission denied error. 

Wondering if a plan to support this is available or in the roadmap or are we off to fend to for ourselves as a user of your platform?

**Comment by toote** [comment]
Hi @ShadySQL, sorry for the delay in getting back to you.

Mounting the docker socket in a job is not only supported but also actually used, albeit you need to be aware of some security implications and considerations with regards to mounting volumes and paths when doing that.

It is very likely that the permission denied error you got was because the user the buildkite-agent is running as does not have permissions to read that socket. If that is not the case, let us know so that we can further investigate.
