### ISSUE TITLE
`.ssh/known_hosts` mounted in wrong location when both `mount-ssh-agent` and `user` are used

### ISSUE THREAD

**Issue by jfirebaugh** [buildkite-plugins/docker-buildkite-plugin#232]
It's always mounted to `/root/.ssh/known_hosts`:

https://github.com/buildkite-plugins/docker-buildkite-plugin/blob/ddc89c23e1cabddc204f146f61e8e5691722fc35/hooks/command#L257

Instead, if `BUILDKITE_PLUGIN_DOCKER_USER` is set, it should be mounted to `/home/${BUILDKITE_PLUGIN_DOCKER_USER}/.ssh/known_hosts`.

**Comment by toote** [comment]
Quite an oversight on our part! Thanks for letting us know.

Unfortunately there is also no guarantee that the home folder of the user being used in the container maps to that path. So instead of hardcoding it that way, I created PR #233 to change the `mount-ssh-agent` option so that you can specify the home folder on which that file will be mounted. While it does add a little bit more configuration on the plugin, it guarantees to be flexible for all use-cases of the feature. What do you think?

**Comment by jfirebaugh** [comment]
Sounds good to me, thanks!

**Comment by jfirebaugh** [comment]
BTW, docker-compose-buildkite-plugin has a similar issue.
