### ISSUE TITLE
Support for other docker commands than docker run

### ISSUE THREAD

**Issue by linus345** [buildkite-plugins/docker-buildkite-plugin#253]
Hey, are there any plans to support other docker commands then running a command in a container? For example introducing support for `docker load`. This would be useful in cases where you want to load a docker image before running a command in a container.

If there's no plans to add this, would you accept a PR introducing it if I opened one up?

**Comment by toote** [comment]
That is quite an interesting idea and we would be more than happy to review a PR if you create one.

Note, though that running a `docker load` on its own without an actual command for the plugin to take care might not make sense. It is possible that the clarification is not necessary, but I believe it is necessary because `command` is a term that has many meanings in this context (`docker` cli subcommand, command hook and actual step's command). I think that if you create a PR explaining the use case and proper tests we can continue the discussion there as well :)

**Comment by linus345** [comment]
Created a PR for this #254, would appreciate any feedback you have
