### ISSUE TITLE
Plugin doesn't correctly bubble up Docker Hub Rate Limiting Error

### ISSUE THREAD

**Issue by HugeIRL** [buildkite-plugins/docker-buildkite-plugin#272]
If you get rate limited from Docker Hub: https://www.docker.com/increase-rate-limits/

The error you get from the plugin is a bit misleading:
`Error response from daemon: pull access denied for api, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

We should actually either bubble up the rate limit error (if it exists), or be more specific on the error so folks know it might be a rate limiting issue. If you don't know that you're being rate limited from Docker, this error isn't as clear as it could be.

**Comment by toote** [comment]
@HugeIRL I couldn't find any part of the error you pasted anywhere in the code so it would appear as that is exactly the error being generated by docker so there isn't much that the plugin can do about the message being printed if it doesn't mention anywhere that the root cause was throttling.  As mentioned in the link you pasted, if the request gets throttled, the client will print out one of two errors that make it clear that you are hitting some kind of limit.

From what I could find, in the error you are getting the `api` of the `_denied for api_` means that the plugin tried to run `docker pull api` which probably does not exist and that is why you got the message you got and not an actual throttling error.
