### ISSUE TITLE
WORKDIR overwritten if not explicitly set

### ISSUE THREAD

**Issue by aussiegeek** [buildkite-plugins/docker-buildkite-plugin#37]
I have a WORKDIR set in the Docker image I'm wanting to run, and wasn't expecting to have this overwritten

**Comment by toolmantim** [comment]
Ah, sorry about that @aussiegeek. Do you think something like `workdir: false` would be good, or that the default behaviour is too unexpected?

**Comment by lox** [comment]
Hmm, this is a tricky one. Given we mount in the current dir by default, wouldn't it be surprising to not be in that directory by default for docker images with a different `WORKDIR`?

**Comment by aussiegeek** [comment]
In my case, no. I have a WORKDIR set because that's the directory I want to be default

**Comment by grahamegee** [comment]
I have a similar request, an I'm not sure if it's worth creating a new issue for it.

I'm working in a mono-repo where we currently build our docker images from the repo root so that we can copy in shared code. If I use this plugin, the entire repo gets mounted in. I think the ability to specify a sub-directory to mount in would be useful.

**Comment by lox** [comment]
After version 2.0.0 if you specify your own `volumes` to mount in (can be relative to `.`) then we don't set a `WORKDIR`.
